packet: Fix host reference
Fixes the following error:

    Error: Missing required argument

      on main.tf line 44, in resource "packet_device" "test":
      44:     connection {

    The argument "host" is required, but no definition was found.

Signed-off-by: Joe Stringer <joe@cilium.io>